//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QlikConversationService.Multilanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QlikConversationService.Multilanguage.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK {0}, don&apos;t worry, I will notify you if {1}.
        /// </summary>
        internal static string alertAdknowledge {
            get {
                return ResourceManager.GetString("alertAdknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And I have found this report with more detailed information..
        /// </summary>
        internal static string alertDocMessage {
            get {
                return ResourceManager.GetString("alertDocMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check the alert format, it should be something like: /alert Sales 3%.
        /// </summary>
        internal static string alertInputError {
            get {
                return ResourceManager.GetString("alertInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! I have just seen that.
        /// </summary>
        internal static string alertSendMessage {
            get {
                return ResourceManager.GetString("alertSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app with Id {0} could not been opened.
        /// </summary>
        internal static string appOpenAppError {
            get {
                return ResourceManager.GetString("appOpenAppError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am now using the app {0}.
        /// </summary>
        internal static string appOpenedApp {
            get {
                return ResourceManager.GetString("appOpenedApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an application.
        /// </summary>
        internal static string appSelectApp {
            get {
                return ResourceManager.GetString("appSelectApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string bsButtonNo {
            get {
                return ResourceManager.GetString("bsButtonNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string bsButtonYes {
            get {
                return ResourceManager.GetString("bsButtonYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have found some news about {0}:.
        /// </summary>
        internal static string bsFoundNews {
            get {
                return ResourceManager.GetString("bsFoundNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you also want to search news about {0}?.
        /// </summary>
        internal static string bsWantToSearch {
            get {
                return ResourceManager.GetString("bsWantToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by.
        /// </summary>
        internal static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bye.
        /// </summary>
        internal static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the analysis sheet.
        /// </summary>
        internal static string cnvAnalysisError {
            get {
                return ResourceManager.GetString("cnvAnalysisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no rights to create a sheet in this app :-(.
        /// </summary>
        internal static string cnvAnalysisNoRights {
            get {
                return ResourceManager.GetString("cnvAnalysisNoRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, I have prepared this &lt;a href=&quot;{1}&quot;&gt;Analysis sheet&lt;/a&gt; for you. I hope you like it..
        /// </summary>
        internal static string cnvAnalysisResult {
            get {
                return ResourceManager.GetString("cnvAnalysisResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet for Bot user {0}.
        /// </summary>
        internal static string cnvAnalysisSheetDescription {
            get {
                return ResourceManager.GetString("cnvAnalysisSheetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the analysis the Qlik Sense Bot made based on your preferences.
        /// </summary>
        internal static string cnvAnalysisSheetTextboxText {
            get {
                return ResourceManager.GetString("cnvAnalysisSheetTextboxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis made by the Qlik Sense Bot.
        /// </summary>
        internal static string cnvAnalysisSheetTextboxTitle {
            get {
                return ResourceManager.GetString("cnvAnalysisSheetTextboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis prepared by the Qlik Sense Bot for {0}.
        /// </summary>
        internal static string cnvAnalysisSheetTitle {
            get {
                return ResourceManager.GetString("cnvAnalysisSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, but I hope this does not happen again.
        /// </summary>
        internal static string cnvApologizeAnswer {
            get {
                return ResourceManager.GetString("cnvApologizeAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m very sad, now I do not feel like answering :-(.
        /// </summary>
        internal static string cnvApologizeOrNoAnswer {
            get {
                return ResourceManager.GetString("cnvApologizeOrNoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :-(
        ///I prefer not to answer this type of questions. I am a robot, but I have my litte heart..
        /// </summary>
        internal static string cnvBadwords {
            get {
                return ResourceManager.GetString("cnvBadwords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, I think the best way is to go &lt;a href=&quot;{1}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string cnvContactQlik {
            get {
                return ResourceManager.GetString("cnvContactQlik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the chart.
        /// </summary>
        internal static string cnvCreateChartError {
            get {
                return ResourceManager.GetString("cnvCreateChartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no rights to create a chart in this app :-(.
        /// </summary>
        internal static string cnvCreateChartNoRights {
            get {
                return ResourceManager.GetString("cnvCreateChartNoRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, I have prepared this &lt;a href=&quot;{1}&quot;&gt;Chart&lt;/a&gt; for you. I hope you like it..
        /// </summary>
        internal static string cnvCreateChartResult {
            get {
                return ResourceManager.GetString("cnvCreateChartResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet for Bot user {0}.
        /// </summary>
        internal static string cnvCreateChartSheetDescription {
            get {
                return ResourceManager.GetString("cnvCreateChartSheetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis prepared by the Qlik Sense Bot for {0}.
        /// </summary>
        internal static string cnvCreateChartSheetTitle {
            get {
                return ResourceManager.GetString("cnvCreateChartSheetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry but I do not know wich analysis to talk about with other people. Ask for a chart first, and then we can join a group to discuss about it..
        /// </summary>
        internal static string cnvCreateGroupNoChart {
            get {
                return ResourceManager.GetString("cnvCreateGroupNoChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello all, I have been invited by {0} to join this group. Here you have the last chart we were talking, and that we want to share with you. Just write a / at the begining of any sentence if you want me to interpret it..
        /// </summary>
        internal static string cnvCreateGroupWelcome {
            get {
                return ResourceManager.GetString("cnvCreateGroupWelcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current selections are: {0}.
        /// </summary>
        internal static string cnvCurrentSelections {
            get {
                return ResourceManager.GetString("cnvCurrentSelections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no filters at this moment.
        /// </summary>
        internal static string cnvCurrentSelectionsEmpty {
            get {
                return ResourceManager.GetString("cnvCurrentSelectionsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1} with {2}.
        /// </summary>
        internal static string cnvMeasure4ElementNewsSearch {
            get {
                return ResourceManager.GetString("cnvMeasure4ElementNewsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, if you want to know more about myself, I suggest you go &lt;a href=&quot;{1}&quot;&gt;here&lt;/a&gt;.
        /// </summary>
        internal static string cnvPersonalInformation {
            get {
                return ResourceManager.GetString("cnvPersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} for {1}.
        /// </summary>
        internal static string cnvShowChartNewsSearch {
            get {
                return ResourceManager.GetString("cnvShowChartNewsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demo mode activated. Only my creator will be able to use me..
        /// </summary>
        internal static string DemoActivated {
            get {
                return ResourceManager.GetString("DemoActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now I need your location.
        /// </summary>
        internal static string gasAccessLocation {
            get {
                return ResourceManager.GetString("gasAccessLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow send location to Bot.
        /// </summary>
        internal static string gasButtonLocation {
            get {
                return ResourceManager.GetString("gasButtonLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m sorry, some problem happened when looking for petrol stations.
        /// </summary>
        internal static string gasError {
            get {
                return ResourceManager.GetString("gasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to see all before choosing?.
        /// </summary>
        internal static string gasSeeAll {
            get {
                return ResourceManager.GetString("gasSeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I have no location, so I cannot get the closest petrol stations..
        /// </summary>
        internal static string gasSorryNoLocation {
            get {
                return ResourceManager.GetString("gasSorryNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which distance to search from your location?.
        /// </summary>
        internal static string gasWhichDistance {
            get {
                return ResourceManager.GetString("gasWhichDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I couldn&apos;t find any {0} in {1} Km around.
        /// </summary>
        internal static string geoElementNotFound {
            get {
                return ResourceManager.GetString("geoElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, you can go to this &lt;a href=&quot;{1}&quot;&gt;Analysis Sheet&lt;/a&gt; if you want more information..
        /// </summary>
        internal static string geoGotoAnalysisSheet {
            get {
                return ResourceManager.GetString("geoGotoAnalysisSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string kpiAnalysis {
            get {
                return ResourceManager.GetString("kpiAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think you want a chart, but I don&apos;t know which dimension to use, so I will better show you: .
        /// </summary>
        internal static string kpiChartWithoutDimension {
            get {
                return ResourceManager.GetString("kpiChartWithoutDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        internal static string kpiCost {
            get {
                return ResourceManager.GetString("kpiCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has changed by.
        /// </summary>
        internal static string kpiHasChangedMoreThan {
            get {
                return ResourceManager.GetString("kpiHasChangedMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think you want a particular data, but I don&apos;t know for which element, so I will better show you: .
        /// </summary>
        internal static string kpiM4EWithoutElement {
            get {
                return ResourceManager.GetString("kpiM4EWithoutElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string kpiMargin {
            get {
                return ResourceManager.GetString("kpiMargin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry, but there are not KPIs defined.
        /// </summary>
        internal static string kpiNoMeasuresDefined {
            get {
                return ResourceManager.GetString("kpiNoMeasuresDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string kpiSales {
            get {
                return ResourceManager.GetString("kpiSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Acum.
        /// </summary>
        internal static string kpiSalesAcum {
            get {
                return ResourceManager.GetString("kpiSalesAcum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a dimension.
        /// </summary>
        internal static string kpiSelectDimension {
            get {
                return ResourceManager.GetString("kpiSelectDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a measure.
        /// </summary>
        internal static string kpiSelectMeasure {
            get {
                return ResourceManager.GetString("kpiSelectMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Sheet.
        /// </summary>
        internal static string kpiSelectSheet {
            get {
                return ResourceManager.GetString("kpiSelectSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a Story.
        /// </summary>
        internal static string kpiSelectStory {
            get {
                return ResourceManager.GetString("kpiSelectStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, &lt;a href=&apos;{1}&apos;&gt;Here&lt;/a&gt; you have a link to analyze all the information freely..
        /// </summary>
        internal static string kpiShowAnalysis {
            get {
                return ResourceManager.GetString("kpiShowAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, &lt;a href=&apos;{1}&apos;&gt;Here&lt;/a&gt; you have a link to open the Sheet..
        /// </summary>
        internal static string kpiShowSheet {
            get {
                return ResourceManager.GetString("kpiShowSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, &lt;a href=&apos;{1}&apos;&gt;Here&lt;/a&gt; you have a link to open the Story..
        /// </summary>
        internal static string kpiShowStory {
            get {
                return ResourceManager.GetString("kpiShowStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string kpiSummary {
            get {
                return ResourceManager.GetString("kpiSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current sales are {0}, with a 3,2% increment over last week.
        ///The fulfillment is 43% over the weekly goal..
        /// </summary>
        internal static string kpiSummaryMessage {
            get {
                return ResourceManager.GetString("kpiSummaryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current {0} value is unknown.
        /// </summary>
        internal static string kpiUnknownMessage {
            get {
                return ResourceManager.GetString("kpiUnknownMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current {0} value is {1}.
        /// </summary>
        internal static string kpiValueMessage {
            get {
                return ResourceManager.GetString("kpiValueMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        internal static string nlAnd {
            get {
                return ResourceManager.GetString("nlAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, all filters removed.
        /// </summary>
        internal static string nlClearFilters {
            get {
                return ResourceManager.GetString("nlClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK, I have removed the filter by {0}.
        /// </summary>
        internal static string nlClearOneFilter {
            get {
                return ResourceManager.GetString("nlClearOneFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have filtered now {0} to {1}.
        /// </summary>
        internal static string nlFilterApplied {
            get {
                return ResourceManager.GetString("nlFilterApplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have found a chart that could be useful to analyse this information:
        ///The chart is called &quot;{0}&quot;
        ///and you can open it here: {1}.
        /// </summary>
        internal static string nlGetChart {
            get {
                return ResourceManager.GetString("nlGetChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I have not found fields for a chart that meets your request. Try other measure and/or dimension.
        /// </summary>
        internal static string nlGetChartNotFound {
            get {
                return ResourceManager.GetString("nlGetChartNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think you want to know {0} when {1}.
        ///In that case, the {2} is {3}.
        /// </summary>
        internal static string nlGetElement {
            get {
                return ResourceManager.GetString("nlGetElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is greater than {1}.
        /// </summary>
        internal static string nlGetElementAboveValue {
            get {
                return ResourceManager.GetString("nlGetElementAboveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is lower than {1}.
        /// </summary>
        internal static string nlGetElementBelowValue {
            get {
                return ResourceManager.GetString("nlGetElementBelowValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is equal to {1}.
        /// </summary>
        internal static string nlGetElementMoreFilter {
            get {
                return ResourceManager.GetString("nlGetElementMoreFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I have not found fields for an element that meets your request. Try other measure and/or dimension.
        /// </summary>
        internal static string nlGetElementNotFound {
            get {
                return ResourceManager.GetString("nlGetElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, I have not found fields for a dimension that meets your request. Try another dimension..
        /// </summary>
        internal static string nlGetListNotFound {
            get {
                return ResourceManager.GetString("nlGetListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} is {1}. The lowest {2} is {3} with {0} of {4}.
        /// </summary>
        internal static string nlgInterpretDataAscending {
            get {
                return ResourceManager.GetString("nlgInterpretDataAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total {0} is {1}. The highest {2} is {3} with {0} of {4}.
        /// </summary>
        internal static string nlgInterpretDataDescending {
            get {
                return ResourceManager.GetString("nlgInterpretDataDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next one is {0} with {1}, that is {2} higher..
        /// </summary>
        internal static string nlgInterpretDataNextAscending {
            get {
                return ResourceManager.GetString("nlgInterpretDataNextAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next one is {0} with {1}, that is {2} lower..
        /// </summary>
        internal static string nlgInterpretDataNextDescending {
            get {
                return ResourceManager.GetString("nlgInterpretDataNextDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bottom {0} by {1} are:.
        /// </summary>
        internal static string nlgInterpretDataRankingAscending {
            get {
                return ResourceManager.GetString("nlgInterpretDataRankingAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The top {0} by {1} are:.
        /// </summary>
        internal static string nlgInterpretDataRankingDescending {
            get {
                return ResourceManager.GetString("nlgInterpretDataRankingDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} with {1} of {2}.
        /// </summary>
        internal static string nlgInterpretDataRankingList {
            get {
                return ResourceManager.GetString("nlgInterpretDataRankingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the list of {0}, up to {1} elements:.
        /// </summary>
        internal static string nlgShowListOfElements {
            get {
                return ResourceManager.GetString("nlgShowListOfElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think you want to know a kpi value, but I do not understand which one.
        /// </summary>
        internal static string nlMeasureNotFound {
            get {
                return ResourceManager.GetString("nlMeasureNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not understand you, could you try again with other question?.
        /// </summary>
        internal static string nlMessageNotManaged {
            get {
                return ResourceManager.GetString("nlMessageNotManaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No filter to apply.
        /// </summary>
        internal static string nlNoFilterToApply {
            get {
                return ResourceManager.GetString("nlNoFilterToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no filter by {0}.
        /// </summary>
        internal static string nlNoFilterToClear {
            get {
                return ResourceManager.GetString("nlNoFilterToClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, now we are analyzing {0}.
        /// </summary>
        internal static string nlTotalFilters {
            get {
                return ResourceManager.GetString("nlTotalFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with.
        /// </summary>
        internal static string nlWith {
            get {
                return ResourceManager.GetString("nlWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No title.
        /// </summary>
        internal static string ObjectWithNoTitle {
            get {
                return ResourceManager.GetString("ObjectWithNoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received choosen inline result:.
        /// </summary>
        internal static string Receivedchooseninlineresult {
            get {
                return ResourceManager.GetString("Receivedchooseninlineresult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, here you have your report {1}.
        /// </summary>
        internal static string reportHereYourReport {
            get {
                return ResourceManager.GetString("reportHereYourReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a report.
        /// </summary>
        internal static string reportSelectReport {
            get {
                return ResourceManager.GetString("reportSelectReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry, but you are not allowed to use this Bot.
        /// </summary>
        internal static string secUserNotAllowed {
            get {
                return ResourceManager.GetString("secUserNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the KPI you want to know.
        /// </summary>
        internal static string SelectKPI {
            get {
                return ResourceManager.GetString("SelectKPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am sorry, but now I am in demo mode and only take orders from my lord and master ;-).
        /// </summary>
        internal static string SorryDemoMode {
            get {
                return ResourceManager.GetString("SorryDemoMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, but I don&apos;t know where are you..
        /// </summary>
        internal static string SorryNoLocation {
            get {
                return ResourceManager.GetString("SorryNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you.
        /// </summary>
        internal static string ThankYou {
            get {
                return ResourceManager.GetString("ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=\&quot;{0}\&quot;&gt;Click here to create a group to collaborate with other people&lt;/a&gt;.
        /// </summary>
        internal static string urlCreateGroup {
            get {
                return ResourceManager.GetString("urlCreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;closest Petrol Stations&lt;/a&gt;.
        /// </summary>
        internal static string urlGasMapAfter {
            get {
                return ResourceManager.GetString("urlGasMapAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, here you have the &lt;a href=&apos;.
        /// </summary>
        internal static string urlGasMapBefore {
            get {
                return ResourceManager.GetString("urlGasMapBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;closest Petrol Stations&lt;/a&gt;.
        /// </summary>
        internal static string urlGasMapInlineAfter {
            get {
                return ResourceManager.GetString("urlGasMapInlineAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @{0}, here you also have the &lt;a href=&apos;.
        /// </summary>
        internal static string urlGasMapInlineBefore {
            get {
                return ResourceManager.GetString("urlGasMapInlineBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;&gt;Prices&lt;/a&gt;.
        /// </summary>
        internal static string urlGasTableAfter {
            get {
                return ResourceManager.GetString("urlGasTableAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And here you have also a table with the last &lt;a href=&apos;.
        /// </summary>
        internal static string urlGasTableBefore {
            get {
                return ResourceManager.GetString("urlGasTableBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///   Inline mode, write: @QlikSenseBot [search data]
        ///
        ///Or try asking for the information directly, I&apos;ll try to understand you. Some examples:
        ///   Show my KPIs.
        ///   I want to know avg sales.
        ///   Could you show me revenue by product?
        ///   Show my reports.
        ///   Who are my best customers?
        ///.
        /// </summary>
        internal static string UsageInstructions {
            get {
                return ResourceManager.GetString("UsageInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}, How are you doing?
        ///Tell me how can I help you. (type help for options).
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are welcome.
        /// </summary>
        internal static string YoureWelcome {
            get {
                return ResourceManager.GetString("YoureWelcome", resourceCulture);
            }
        }
    }
}
